### ISSUE TITLE
Parser Does Not Handle Left-Recursion

### ISSUE THREAD

**Issue by sunjay** [pest-parser/pest#101]
[Left-recursion is a known problem with recursive descent parsers](http://www.personal.kent.edu/~rmuhamma/Compilers/MyCompiler/leftRecursion.htm). I managed to run into this today so I thought I would report the case that goes wrong:

```rust
#[macro_use]
extern crate pest;

use pest::prelude::*;

impl_rdp! {
    grammar! {
        foo = { bar | ['a'..'z'] }
        bar = { foo ~ ['0'..'9'] }
    }
}

fn main() {
    let mut parser = Rdp::new(StringInput::new("abc1"));
    assert!(parser.foo());
    assert!(parser.end());
}
```

Running this results in:
```
thread 'main' has overflowed its stack
fatal runtime error: stack overflow
```

Would it be possible to catch simple cases of this in 1.0.0? Sometimes it's not obvious that you're doing left-recursion.

I am using pest v0.4.1.

**Comment by dragostis** [comment]
It's already implemented in the PR.

**Comment by sunjay** [comment]
Great!

**Comment by sunjay** [comment]
If you're thinking about adding this, the discussion here may be of some use: https://github.com/pegjs/pegjs/issues/231

**Comment by dragostis** [comment]
Right now, I'm not in favour of adding left-recursion. Even though there is a particular implementation that offers a nice syntax, the potential performance impact is not worth having to explain how left-recusion works in this case to the basic PEG user.

I have a proposal:

* consider improving operator syntax
* suggest operator syntax when left-recursion is detected

The operator syntax could be improved in a similar way to the way to the precedence example in [this paper](https://arxiv.org/pdf/1207.0443.pdf). pest would then detect the syntax and implement the usual precedence climbing algorithm. However, this syntax would have to be completely unambiguous and predictable.

The solution should stick to pest's values: be the fastest possible parser while providing a predictable and newbie-friendly environment for people new to grammars.

**Comment by sunjay** [comment]
I agree that implementing left recursion is quite involved and could have a serious performance impact.

I think no matter what, we should make sure we at least:
* Detect left recursion (both direct and indirect) and print an error because it's important for people to know at compile time, not run time
* Document the common use cases and alternatives: binary operators (use precedence climbing), unary operators (use slightly more complex rule structure)

All of that being said, **if anyone can come up with an implementation that solves the problem and addresses most of our concerns above, pull requests are welcome.** The maintainers of pegjs had someone else come in and attempt it. You can see the details in [the issue thread](https://github.com/pegjs/pegjs/issues/231).

**Comment by sunjay** [comment]
Also, though I just said binary operators, we should in particular make sure to add some documentation about left associative binary operators as this is a particular pain point without left recursion. 

Example:
The `.` operator for field access must group to the left. `a.b.c = (a.b).c`.

**Comment by sunjay** [comment]
Though the stack overflow at runtime should be fixed in a PR (https://github.com/pest-parser/pest/pull/88 ?), the actual implementation of this as a feature is still up for discussion/implementation. **If you have an idea about how this could work, please feel free to comment here and we'll discuss it with you.**

This issue is on hold until someone can provide a suitable solution.

**Comment by dragostis** [comment]
Right now, I'm thinking about the following solution:

* implement really basic grammar for left-recusrive cases (`expr ~ ("." ~ ident)*` for the `.` operator)
* have left-recursion detection in the derive (already implemented)
* parse the generated tokens with the `PrecClimber` for precedence and associativity (already implemented)

**Comment by dragostis** [comment]
Left-recursion detection and precedence climbing API should mitigate this issue.

**Comment by Victor-Savu** [comment]
Should this be closed now?

**Comment by dragostis** [comment]
@Victor-Savu I guess it can get closed for the time being.

**Comment by canndrew** [comment]
Sorry to bump an ancient issue, but it would be really nice if left-recursion "just worked". For example, consider a language consisting of sequences of `1`s separated by `+`s, eg.

    1 + 1 + 1 + 1

If I want to write a parser that parses this left-associatively, eg as:

          +
         / \
        +   1
       / \
      +   1
     / \
    1   1

Then I should just be able to write:

    one = { "1" }
    add = { expr ~ "+" ~ one }
    expr = { add | one }

Obviously this fails due to the left-recursion (which is better than silently compiling and causing a stack overflow at runtime, so thanks for that), but I think it would be possible to compile this so that it does what I intended. Rules that do left-recursion would need to be able to detect when they've been re-entered without consuming any input so that they can save the current parsing state and fail. Then, when they exit the outer instance of the rule with success, try to restore the old parsing state using the successful parse now as the return value of the inner instance of the rule, then see if it can successfully keep parsing until it returns from the outer instance again. Actually implementing that in terms of functions would require some kind of setjmp/longjmp nastiness (except jumping up the stack instead of down) so it would probably be best to compile left-recursive rules into state machines instead (so that states can be saved/restored). I don't know what the efficiency cost of that would be.

Could this be considered for implementation? Lots of grammars are left-recursive, it would be nice if pest could hide the complicated details of making them work.

**Comment by CAD97** [comment]
The TL;DR of it: writing a PEG grammar is much more like writing a parser than writing a "traditional" CFG grammar specification. Because of this, you'd write `add = { one ~ ("+" ~ one)* }` instead.

However, there [definitely are techniques for handling non-advancing recursion in PEG transparently](https://github.com/PhilippeSigaud/Pegged/wiki/Left-Recursion#bounded-left-recursion). We're slowly tinkering with a Pest v3 draft, and once we have that, it's definitely on my radar to try out integrating that technique.
