### ISSUE TITLE
Recommended error handling

### ISSUE THREAD

**Issue by emoon** [pest-parser/pest#115]
Hi,

First of all thanks for this great crate! I'm currently using it for a small custom configuration format but planning to use it for bigger things.

One thing I'm wondering a bit about is how the recommended way is to do report errors back to the user. In the documentation there is this example:

```Rust
impl_rdp! {
    grammar! {
        expression = _{ paren ~ expression? } // expression is silent so we'll only have parens
        paren      =  { ["("] ~ expression? ~ [")"] }
    }
}

let mut parser = Rdp::new(StringInput::new("(())()foo"));
                                        //        ^   - Parser should expect a paren at pos 6

assert!(parser.expression()); // the parser goes as deep as it can
assert!(!parser.end());       // end is not reached, so the whole Input was not matched

assert_eq!(parser.expected(), (vec![Rule::paren], 6));
```

But in reality it's usually a bit more complex. Like you have loaded a file and wants to show line, position etc.

I noticed you made some changes that seems related to this here:

https://github.com/pest-parser/pest/commit/93ca432762f8487580db880c529ce894932b495e

But I'm not exactly sure how the suggested way is to use this?

Cheers!

**Comment by dragostis** [comment]
Thank you for your time and glad to see pest being of use. 😃 

Error reporting (in 0.4) works by keeping track of rules that fail at every position in the input as long as the those rules are not silent. In the case where they are silent, they do not get reported. By the current design, the parser only keeps track of the deepest (right-most) errors that occurred. The `expected` method thus returns the rules that failed and the deepest position where this happened.

This is a pretty crude offering and pest 1.0 will improve on it by proving pretty neat error types that get formatted very similarly to rustc (where you can see exactly where the error was in the input). It will also keep track of rules run in predicated (`&` and `!`).

All of this offers pretty decent error reporting out of the box without fiddling too much with the library. However, one can do much more by defining grammar for very specific errors like this:

```
my_rule = { good_rule | possible_errors }
possible_errors = { error1 | error2 | ... }
```

And then, during the token processing phase these very specific errors can be error reported. These errors could be typical mistakes that a user could make, e.g. "variable names cannot start with a number".

I'm currently working on making 1.0 useable: I have some more tinkering to do on the derive, but things look pretty well. 1.0 will break compatibility with 0.4 in a few ways, however:

* grammar will be simplified and precedence climbing removed from grammar definition, but most of the grammar definitions should only require small changes in order to be made compatible
* `process!` macro will be replaced by the new `Pairs`  API
* precedence climbing will be implemented during the processing phase

Hope this sheds some light on the matter. Let me know if you need any help here or on Gitter.

**Comment by emoon** [comment]
Thanks for the reply. That sounds good. I think I will just do some very basic error checking for now and wait for the 1.0 goodies then :)

**Comment by dragostis** [comment]
@emoon Awesome! Working on precedence climbing right now. Working 1.0 build should come relatively soon.

**Comment by emoon** [comment]
👍
