### ISSUE TITLE
Allow arbitrary functions as rules

### ISSUE THREAD

**Issue by jsdw** [pest-parser/pest#119]
Another thing I've bumped into in writing my parser is that I have a bunch of (in my case, approx 50) colours in a big list that I'd like to parse as some token. Rather than writing the list out again in the rules eg:

```
impl_rdp!{
    grammar!{
        colours = { ["blue"] | ["red"] | ["green"] ... }
        //...
    }
}
```

I'd like to be able to do something like:

```
impl_rdp!{
    grammar!{
        colours = { [match_colour()] }
        //...
    }
}

// try to match a colour in some list
fn match_colour(input: &Input) -> ? {
    //... this avoids the repetition of listing colours out twice, and provides
    // a general escape hatch for certain tricky cases.
}
```

Currently, I am not aware of any way to avoid duplicating my list of colours, since rules are part of an enum so I can't just manually impl some function which gets used as a rule or anything.

Is there a solution to this that I am missing?

**Comment by dragostis** [comment]
I guess this is one of the drawbacks of the separate grammar approach. The reason why pest is built like this is in order to have a formal grammar definition available at all times which is also the source of truth that the parser uses.

There would be a way of implementing a manual rule, but this would diminish the former advantage.

**Comment by passcod** [comment]
Not applicable in all cases, but could it be possible to retrieve the rule from the grammar and go the other way? So if you have a `colours` grammar rule and also need the list of colours in the Rust part, you could pull the list from the grammar directly.

**Comment by dragostis** [comment]
@passcod That's a really interesting idea and definitely something doable. Do you have anything specific idea in mind?

**Comment by passcod** [comment]
I'm not familiar enough with Pest internals, but I was thinking perhaps exposing the parser AST for a Rule when doing the derive?

**Comment by dragostis** [comment]
This could definitely work. Would be tempted to push this to a tentative v1.1 release.

**Comment by cretz** [comment]
If you are looking for another use case, I have one where I have to make sure a certain unicode property is set on a character.

**Comment by dragostis** [comment]
@cretz Of course. Could you please link the example?

**Comment by cretz** [comment]
Not in front of the spec atm, but I was toying with ECMA script (i.e. JS) and its identifiers must start with a code point that has the start property.

**Comment by dragostis** [comment]
I think that Unicode start and continue characters should be part of pest's defaults.

**Comment by cretz** [comment]
Maybe, but I think a form of callback or conditional where you can inspect the stack has lots of benefits. Sure you don't have a 100% separate grammar, but i think that's better than having to abandon pest files altogether if you need the tiniest flexibility.

**Comment by dragostis** [comment]
@cretz I have two arguments against a full blown callback implementation in the grammar.

The first is that grammars are currently pure. It's very easy to see, from a formal perspective, what the grammar actually is. This is a considerable advantage over other parsers, since you don't need to maintain an always up to date formalism since you already have one.

The second argument would be that more complex handling can be done after the main parsing. For example, in pest_derive, there is a validation step that can generate errors, and all of this is very easy to include with pest's Error type.

Now, I see how having more flexibility would be useful, but I think that the best approach here would be to be able to extract more information from the actual grammar which I've been looking into recently.

**Comment by Keats** [comment]
Another example of a usecase for that: https://github.com/Keats/tera/issues/343

Tera uses `{{`, `{%` etc for delimiters which conflict with some other tools. Jinja2 allows setting the delimiter to something else to avoid that issue but, without being able to parametrize the parser my only solution is to duplicate my `tera.pest` and create 2 parsers: one for the default delimiters and an alternative one.

**Comment by dragostis** [comment]
@Keats, you can use `PUSH` and `PEEK` for this specific use case.

**Comment by Keats** [comment]
Is there some docs other than https://docs.rs/pest_derive/1.0.8/pest_derive/#push-pop-and-peek on this feature?

**Comment by dragostis** [comment]
Not really, but feel free to reach out on Gitter for help!
