### ISSUE TITLE
Reporting leaf rules in parse errors

### ISSUE THREAD

**Issue by joliss** [pest-parser/pest#140]
If I define the following rules:

```
a = { "a" }
b = { "b" }
s = { a ~ b }
```

and run `MyParser::parse_str(Rule::s, "x")`, it returns an error saying "expected s":

```
 --> 1:1
  |
1 | x
  | ^---
  |
  = expected s
```

I was expecting it to report the leaf rule and say "expected a".

I can get the behavior I want by silencing `s` with `s = _{ a ~ b }`, but I was under the impression that silencing should only be needed for leaf nodes that I'm not interested in, like `whitespace`.

I'm not sure if this is a bug or if it's working as intended. Perhaps my expectations are colored from using rust-peg before.

**Comment by dragostis** [comment]
The way this works right now is that it reports the superior rule if the leaves have not made any progress. This behavior is useful when you have multiple choices and you cannot discern which one is more probable to be the one that should match. However, rules that have only one possible child should report the child. Right now, there is no easy way to introduce this behavior which is why I'm still considering whether or not to push it for a later release.

**Comment by joliss** [comment]
I see... With the caveat that I'm not a parser expert, I wonder if "have we made progress" is a good heuristic for determining what to report.

Say we are trying to parse a `block` rule, defined as follows:

```
block = { (statement ~ ";")* ~ eoi }
statement = { read_statement | write_statement }
read_statement = { "read" }
write_statement = { "write" }
```

* If we try to parse `"read;foo;"`, we get the following parse error:

    ```
     --> 1:6
      |
    1 | read;foo;
      |      ^---
      |
      = expected statement
    ```

    My intuition is that "expected read_statement or write_statement" may be clearer, but one can argue that "expected statement" does the job here.

* However, surprisingly, if we parse `"foo;"`, we get a *different* parse error:

    ```
     --> 1:1
      |
    1 | foo;
      | ^---
      |
      = expected block
    ```

    It seems surprising to me that the error reporting changes depending on whether the error happens in the first statement or in a subsequent statement. I want to argue that the fact that we haven't made progress into the `block` rule shouldn't change how we report errors.

    I realize that the behavior you're proposing (automatic descent into leaves for single-choice rules) fixes this. However, one can probably construct examples where `block` is defined as a multiple-choice rule.

**Comment by dragostis** [comment]
I've closed this for now, having implemented the solution I told you about. If anything else comes up, feel free to open another issue or reopen this one.

**Comment by joliss** [comment]
Very cool, thank you!

In the following edge case, pest still reports the parent rule -- this is the minimal example I could find:

```
s = { maybe_a ~ b }
maybe_a = { a? }
a = { "a" }
b = { "b" }
```

Parsing with `MyParser::parse_str(Rule::s, "x")` yields

```
 --> 1:1
  |
1 | x
  | ^---
  |
  = expected s
```

I was expecting it to say "expected a or b".

Curiously, if instead you define

```diff
-maybe_a = { a? }
+maybe_a = { "a"? }
```

then it says "expected b".

**Comment by dragostis** [comment]
That is normal behavior. Let break it down:

In the first case, the parser know that two rules, `a` and `b`, were executed and failed in the `s` rule. Because none of them made progress, it reports `s`.

In the second case, `a` is no longer there two produce a token, so `b` is reported for being the only child that produced a token.

For the behavior you mentioned one can make `s` and `maybe_a` silent.

**Comment by joliss** [comment]
Thank you, that makes sense now!
