### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by defyrlt** [pest-parser/pest#149]
Hi. I'm playing around with the example from README. Here's the code and grammar:
```rust
extern crate pest;
#[macro_use]
extern crate pest_derive;

use pest::Parser;

#[derive(Parser)]
#[grammar = "language.pest"]
struct IdentParser;

fn main() {
    let pairs = IdentParser::parse_str(Rule::account, "Account:abcd")
                    .unwrap_or_else(|e| panic!("{}", e));

    // Because ident_list is silent, the iterator will contain idents
    for pair in pairs {
        // A pair is a combination of the rule which matched and a span of input
        println!("Rule:    {:?}", pair.as_rule());
        println!("Span:    {:?}", pair.clone().into_span());
        println!("Text:    {}", pair.clone().into_span().as_str());

    }
}
```

```
alpha = { 'a'..'z' | 'A'..'Z' }
digit = { '0'..'9' }
whitespace = _{ " " | "\t" | "\r" | "\n" }

ident = { (alpha | digit)+ }

account = { "Account:" ~ ident ~ whitespace }
```

Note that my input doesn't have whitespace at the end. When I run it, it says that it expected `alpha` or `digit`, while it should complain about `whitespace`, unless I'm missing something.
```
thread 'main' panicked at ' --> 1:13
  |
1 | Account:abcd
  |             ^---
  |
  = expected alpha or digit', src/main.rs:13:40
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by dragostis** [comment]
`whitespace` is silent which is why it isn't error reported.

**Comment by dragostis** [comment]
You can easily avoid this issue by having an extra rule:

```rust
whitespace_I_care_about = { whitespace }

account = { "Account:" ~ ident ~ whitespace_I_care_about }
```

**Comment by hardliner66** [comment]
@dragostis 
I just spent an hour because I couldn't figure out why I'm getting parse errors.

While it makes sense to me to not include certain things (whitespace, semicolon, etc.) into the AST, I can't think of a single case where it would make sense to not print to the user why exactly parsing went wrong. As the developer of a tool I might figure it out, but as user of a tool there is no way to actually know why I'm getting this error.

Currently if I want to have correct reporting of a missing semicolon and where that simcolon should be, i have to use rules like this:
```
// this needs to be silent
semicolon_silent = _{WHITESPACE* ~ ";"}

// this needs to have the correct name, which I want to display to the enduser
semicolon = {WHITESPACE* ~ ";"}

// this also needs to be silent and I have to remember to putter the silent inner rule first, so that it won't show up in parse output
semicolon_helper = _{semicolon_silent | semicolon}
```

Depending on the language I'm parsing, it's not feasable to create such helper rules for everything. And on top of that it is error prone.

So I think this should be fixed and in the meantime it should be stated in the docs that silent works that way and how to work around that (like the rule example I used above).

**Comment by hardliner66** [comment]
I just found an alternative for creating such rules, without having to duplicate the rule itself:
```
semicolon_silent = _{WHITESPACE* ~ ";"}
semicolon = {semicolon_silent}
semicolon_helper = _{semicolon_silent | semicolon}
```

**Comment by hardliner66** [comment]
I also found that this doesn't work for WHITESPACE when explicitly specified. It seems like error reporting works differently if WHITESPACE is involved in any of the rules.

**Comment by dragostis** [comment]
@hardliner66, interesting alternative. Usually, for rules that can appear in small number of places, it's easy enough to just ignore the generated token pair like the `semicolon` example. With a rule as often found as `WHITESPACE`, that's not really feasible, this also leads to an interesting questions: if a rule can pretty much be present everywhere, does the error reporting give any extra information by including it in the report?

Maybe there's real need for a silent-but-reported kind of rule, but my hesitation for including that in the first place was to not introduce extra syntax and complexity.

**Comment by hardliner66** [comment]
The problem with not reporting the error is, that if you mark things as silent while designing the grammar, you only get reports of whole rules failing. Depending on what you actually need, this might bubble up until the top level rule. And just being told that your top level rule somehow doesn't parse, won't help you fix the problem in your grammar design (if there is one) or in the sample input your trying to parse.

So the only ways to get error reporting while designing the grammer is to either use that workaround for everything or to design the grammar with no silent rule at all until every valid input parses, then change everything you don't want to have in your ast to silent and only then start with the implementation.

And if you want to change the grammar, you would likely have to remove every silent marker, redesign the grammar, put the silent markers back in and then fix the implementation.

The silent marker is very important for the language designer, because it simplifies the ast traversal a lot, but at the same time it makes it harder for designer because parsing errors are harder to debug and it makes it harder the user of the language, because he doesn't know that he is missing punctuation somewhere.
