### ISSUE TITLE
"comment" rules don't always seem to get used in 1.0.0-beta.15

### ISSUE THREAD

**Issue by jsdw** [pest-parser/pest#163]
First off, thank you for pest! It's been a pleasure using it.

I started with a .pest file that included:

```
whitespace = _{ " " | "\t" }
comment = _{ block_comment | eol_comment }
    block_comment = _{ "/*" ~ (!"*/" ~ (block_comment | any))* ~ "*/" }
    eol_comment = _{ "//" ~ (!"\n" ~ any)* ~ "\n" }
```

And kept hitting parse errors that suggested that the comment rule was being ignored. After quite a lot of experimentation, I found that I could fix the errors by manually making use of the comment rule as in

```
whitespace = _{ " " | "\t" | a_comment }
a_comment = _{ block_comment | eol_comment }
    block_comment = _{ "/*" ~ (!"*/" ~ (block_comment | any))* ~ "*/" }
    eol_comment = _{ "//" ~ (!"\n" ~ any)* ~ "\n" }
```

(where a_comment works equally well if just "comment").

If you need me to try and reproduce the issue in a minimal example, let me know!

As a side note, I do wonder what the usefulness of having a separate "comment" rule actually is, given that we can achieve the same sort of thing using just whitespace

**Comment by dragostis** [comment]
This seems like a possible bug. A minimal example would be nice if you have the time.

The reason for a separate comment rule is that it gets automatically matched between whitespace runs, but I see how this could be forced into one single rule that either match a whitespace or a comment. What would the name of this rule be? Since pest is still in beta, this could be a decent addition.

Also, glad to hear you've enjoyed using pest. If you have any feedback on how it could be improved apart from this, be sure to leave another issue. 😄

**Comment by jsdw** [comment]
I have created some minimal cases showing the issue:

[tests.zip](https://github.com/pest-parser/pest/files/1403917/tests.zip)

I can't quite work out what's wrong; at a guess I would wonder whether comments are being allowed between things when * is used.

if I had one rule to subsume both "whitespace" and "comment", the best names I can come up with are either "separator" or "between".

Thanks - I'll do that!
