### ISSUE TITLE
using Unicode Category

### ISSUE THREAD

**Issue by ekicyou** [pest-parser/pest#175]
I want to do lexical analysis by the Unicode category.
Is there any way to get enough performance?

```
id          = id1 idn*
id1         = [\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}]
idn         = [\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Mn}\p{Mc}\p{Nd}\p{Pc}\p{Cf}]
```

**Comment by dragostis** [comment]
This is definitely something to be added post `1.0`. Is there any crates that is able to do this on crates.io?

**Comment by ekicyou** [comment]
> Is there any crate that is able to do this on crates.io?

nom+regex is s possible. [re_find_static macro](https://github.com/Geal/nom/blob/d944d2d1176693f7606e7bb739806b9de04719df/src/regexp.rs#L143)

If character matching using function call, it is possible to do the same.
Or, it would be appreciated if you had a peg grammar to convert to a regex call.

**Comment by wirelyre** [comment]
There's the [`unic-ucd-category`](https://crates.io/crates/unic-ucd-category) crate (part of [`unic`](https://crates.io/crates/unic)).

The [`regex`](https://crates.io/crates/regex) crate uses [a special tool](https://crates.io/crates/ucd-generate) to directly parse the Unicode Character Database into Rust code.

**Comment by CAD97** [comment]
I think the best way to go about adding Unicode Property support is to add a new terminal - a regex literal, using the regex crate.

Note that this shouldn't break any complexity promises provided by the PEG grammar structure, as the Rust `regex` crate is non-backtracking.

So, for my identifier rule, instead of writing something like:

```
identifier = @{ identifier_head ~ identifier_tail* }
identifier_head = { 'a'..'z' | 'A'..'Z' }
identifier_tail = { identifier_head | '0'..'9' }
```

I could write the following:

```
identifier = { r"\p{XID_START}\p{XID_CONTINUE}*" }
```

When pest is turning this into parser code, it should prepend a `^` to the regex to anchor it to the start of the input. This will allow the regex crate to use its highly optimized byte-level recognizer.

Of course, this would not preclude using pest's composition tools directly, but in addition to the literal terminal adds another terminal option that gives a bit more power while still being O(1) to match that terminal.

If someone can give me pointers on where to go about adding this new terminal, I'm interested in using it (I think a PEG grammar is just what my project wants!), and I'd love to help with implementing it.

In the mean time, I could dump Unicode categories into pest rules if anyone's interested.

----

And speaking as a co-developer for unic, I can't really recommend `unic-ucd-category` for this use case. For this specific use case, the regex crate beats us out in every possible way currently. We are very much just trying for exposing every bit of information from ICU in a modular way rather than optimization or even stability currently. That plus the limited time either I or Behnam have been able to spend on the project recently... regex is a better fit for this use case.

**Comment by CAD97** [comment]
Here's some _very_ WIP progress (it doesn't even come close to working yet): https://github.com/pest-parser/pest/compare/master...CAD97:regex-terminal

The basic outline that I have drafted out:

- Using a regex terminal adds a peer runtime dependency on regex and lazy_static for the parser
- Collect regex literal terminals in the form of raw strings
  - e.g. `r#"\p{XID_START}\p{XID_CONTINUE}"#`
  - Supporting `#` demarcation is to be nice
- Prepend `^` to regex literal to anchor to start of remaining input
- When "optimizing", associate each unique regex string with a unique ID
- On emitting the parser, create a `lazy_static!`ed array of `Regex` structs
- On starting the parse, dereference that lazy static
- During parse, index into that array to refer to each regex

I'm actually not exactly sure what steps of the parse I've missed that the derive is panicking, but that's pobably partially due to the fact that it's really late now and I'm going to bed as soon as I post this.

<details><summary>Derive panic</summary>

```
error: proc-macro derive panicked
  --> derive\tests\grammar.rs:15:10
   |
15 | #[derive(Parser)]
   |          ^^^^^^
   |
   = help: message: error parsing "grammar.pest"
           
             --> 26:12
              |
           26 | regex = { r"\p{XID_START}\p{XID_CONTINUE}*" }
              |            ^---
              |
              = expected `{`, `}`, `&`, `|`, `?`, `*`, or `+`
```
</details>

**Comment by CAD97** [comment]
OK, I've got a somewhat-working version at #246! I've yet to try _actually_ using it, but the added test rule under `pest_derive` suggests that it's working.

**Comment by dragostis** [comment]
@CAD97 Thank you opening up the discussion and this PR. 🎉Here are my philosophical 2 cents on the matter:

One of the goals with pest was to have a library with a small number of dependencies making it a pretty bare bones solution for parsing. We've also been constantly working on making compilation times smaller since the first alpha releases of pest. The regex crate is an amazing piece of engineering, but it's also a pretty big project with a considerable amount of overlap with pest's functionality. I personally consider a more focused approach to be the winning solution here. What do you think about about using [`regex-syntax`](https://github.com/rust-lang/regex/tree/master/regex-syntax) as a dependency instead? (or maybe even a fork?) From there, we can make direct use of the Unicode ranges without adding needless complexity to the pest crate.

As a side node, one of the first designs with pest was to have a regex-based terminal parser, but I finally went with the current approach because:

* regex knowledge should not be a prerequisite for pest users; pest should be particularly aimed at newcommers
* having a unified, integrated syntax from terminal parsing all the way to high level rules instead of having to combine regex with PEG
* as mentioned in your PR, pest's greediness would be confusing when mixed with regex

Really excited to hear your take and to finally add properties to pest!

**Comment by CAD97** [comment]
Here's a short summary of some of the points I considered before prototyping out the regex terminals:

Reasons not to avoid regex/lazy_static:
- Both crates are version 1.0 with strong promises of stability.
- regex will only effect first-compile times -- subsequent compiles will reuse the compiled crate.
- regex is a rust-lang repository and thus backed by the rust core team.
- As implemented in #246, it's a strictly additive feature to the pest grammar. Everything that worked before still works, and I'd expect the standard style to remain the same, only dropping into regex terminals where required.
- Though regex has a bias towards dense blobs, you [can write good clear regex](https://github.com/behnam/rust-unic/blob/f43e4635b1b28009e639d28e148fc4648260943d/gen/src/source/ucd/mod.rs#L27-L34).
- The public/peer dependencies can be hidden.
  - Add a newtype to pest that just opaquely wraps `regex::Regex`, then
  - Expose a macro `pest_regexes!` or similar that wraps up a set of regexes as in #246.

Reasons to reuse regex
- More often than not, parsing starts off as a blob of regexps to extract information.
- We get the performance of a highly tuned byte-based parser for these property-based terminals.
- Code addition to pest is minimal (I was able to do (most of) it in less than a day with no prior pest internals knowledge!).

Reasons to avoid regex
- Semantics of `+` and `*` repetitions differ between pest and regex, which could be confusing
- Adds a second way of doing produced-terminal parsing (`{r"regex"}` instead of `@{pest}`).

On using `regex-syntax` instead
- The crate is explicitly _not_ stabilized, so this would add a 0.X dependency to chase updates on.

On a more targeted implementation
- I could use [`ucd-generate`](https://crates.io/crates/ucd-generate) to create char-based parsers.
- #197 would be a really interesting way to solve this:
  - Turn binary properties into pest matchers, and
  - Use these external pest files as fragments.
- I'd be happy to maintain these fragments (in @pest-parser or externally)!
- Having done the experimentation around adding regex, this _might_ actually be the best path of action.
- Just translating the property into pest, it gets the pest behavior and optimizations automagically!

**Comment by CAD97** [comment]
I've just created a tool that translates ucd-generate generated tables for binary properties (this includes General_Category value inclusion) into hopefully correct pest code.

https://github.com/CAD97/pest-unicode/tree/master/pest

I'd be perfectly happy to bring that in-tree and have that close #246. Then this issue could be closed when #197 is added -- maybe they could even be default-provided for using.

**Comment by dragostis** [comment]
@CAD97 I quite like this approach. I agree with the arguments about regex and I think that the door is very much open to using it in order to gain better performance without altering the current grammar.

#197 requires some non-trivial amount of redesign in order to implement, I'm afraid. It would probably come into fruition post 2.0 launch, however these ranges could be lazily generated as needed in the grammar that's using the property. I would imagine a Map from property names to pest rules defined in Rust code, similar to [builtins](https://github.com/pest-parser/pest/blob/master/derive/src/generator.rs#L72). After #197, these could be migrated into actual pest grammars.

In terms of optimization, I think it's a good idea to make use of [ucd-trie](https://github.com/BurntSushi/ucd-generate/tree/master/ucd-trie).

**Comment by CAD97** [comment]
Alright, I'll take a look at adding some on-demand builtins for these properties then!

**Comment by dragostis** [comment]
@CAD97 Feel free to experiment with this. I'm far from an expert when it comes to Unicode properties and the opimizations possible, so I'm really excited for your proposal. 😄

**Comment by CAD97** [comment]
I noticed something while doing this:

The set of pest_keywords is { ANY, DROP, EOI, PEEK, PEEK_ALL, POP, POP_ALL, PUSH, skip, SOI }. However, there are already further builtins beyond this: { DIGIT, NONZERO_DIGIT, BIN_DIGIT, OCT_DIGIT, HEX_DIGIT, ALPHA_LOWER } and so on.

(continued on new device)

**Comment by dragostis** [comment]
@CAD97 This sounds great! Having particularly long and many `quote!` macro invocations might affect compile times dramatically, but this is very hard to hypothesize.

**Comment by CAD97** [comment]
I just submitted #247 for the smaller change using `ucd-generate`-generated `ucd-trie` tables to power non-keyword builtins.
