### ISSUE TITLE
Add an HTTP parser to parser_benchmarks

### ISSUE THREAD

**Issue by Geal** [pest-parser/pest#210]
Hello!

I spent some time cleaning up the old nom_benchmarks repository in a more general [parser_benchmarks](https://github.com/Geal/parser_benchmarks). Since we're reaching the point where the various parser libraries reach the same performance, it's getting interesting to have a good way to compare them on the same tests, and transfer techniques from one to the next.

I have added your JSON example and put it to work on the other example files (and added the `canada.json` file you use for your benchmarks): https://github.com/Geal/parser_benchmarks/tree/master/json

Interestingly, I have not been able to make the nom parser faster than the pest one for that file :)

Could you check the benchmark to see if I have not missed anything in how to use pest?
Also, do you think you could contribute a HTTP parser to the repository?

**Comment by dragostis** [comment]
Nice work with the benchmark and thank you for taking the time to do this. 😄 

Everything looks good. You might also want to compare pest against the master branch since there are some performance improvements coming up in the next version.

Regarding the HTTP benchmark, this would have a lower priority for now. We're currently working a lot on improving the developer experience and the docs which is quite harder than I first thought.
