### ISSUE TITLE
Unable to get Span without consuming Pair

### ISSUE THREAD

**Issue by sunjay** [pest-parser/pest#223]
If getting a Span consumes a Pair, I have to choose between getting that Span and getting its inner Pairs. This is counter intuitive given that the two don't really seem related. Sometimes I want to look further into the contents of a pair and also get its position. Can we add a `span(&self)` method (or something) to get the Span of a Pair and still allow you to get its inner Pairs afterwards?

I would be happy to create a PR for this. :smile:

**Comment by dragostis** [comment]
I guess it does make sense for `into_span` to be refactored to `as_span(&self)`. However, the current API let's you do what you want by simply cloning the `Pair` which is a cheap operatio.

**Comment by sunjay** [comment]
@dragostis The PR for this is ready: #224 :smile: :tada:

**Comment by frehberg** [comment]
Dito, the function "Pair::into_inner(self,..)" is consuming the pair. I would like to see a function in API just borrowing the pair, something like "Pair::into_inner(&self, ..)"

**Comment by CAD97** [comment]
This issue was about `into_span`, which got `as_span`, which actually does save an Arc clone. However, `pair.clone().into_inner()` is the exact process that a non-consuming `Pair` to inner `Pairs` would do, so adding a function just for that seems not helpful. The API today encourages the consuming option, which is cheaper, if the outside `Pair` is unneeded afterwards, which results in better code (or at the very least, less optimization work for the compiler).
