### ISSUE TITLE
Update domain URL

### ISSUE THREAD

**Issue by dragostis** [pest-parser/pest#287]
When the new domain is in, update the `homepage` links in all the crates.

**Comment by dragostis** [comment]
Done.

**Comment by tomtau** [comment]
@CAD97 it seems the crates have correct domain https://pest-parser.github.io/ , but I guess this meant to update it to https://pest.rs ?
That domain will expire in October and I'm not sure what the plan is around it... anyway, I guess this can be closed for now, given the github link should still be alive even after the domain expires and it can always be fixed in https://github.com/pest-parser/pest-parser.github.io
