### ISSUE TITLE
Reinforce invariants on Position

### ISSUE THREAD

**Issue by dragostis** [pest-parser/pest#301]
`Position` currently uses `unsafe` in quite a few places. Maybe there is a better way to model this in order to minimize the use of `unsafe` and strengthen its invariants.

**Comment by wisn** [comment]
Is this still going, @dragostis? I'm asking because there is a merged PR already

**Comment by dragostis** [comment]
@wisn, thanks for the ping. I think this is fine. If @CAD97 is fine with the current state of affairs, we can close this.

**Comment by CAD97** [comment]
#383 is a case where one of the expensive correctness checks (gated on debug assertions) is causing unacceptable performance degredation in debug mode (therefore making it useless). (When I added it, I thought/hoped it wasn't on a hot path.)

I think we need to make that invariant obvious on the type so that this sanity check can be removed, and then we can consider this closed.

All that needs to happen performance wise is an `unsafe` path that's used when the invariant is guaranteed (on pain of nasal demons) to hold. A type combining the queue Rc and the input ref to guarantee that the queue refers to that input seems the way to go.
