### ISSUE TITLE
Impossible parse?

### ISSUE THREAD

**Issue by nitingupta910** [pest-parser/pest#308]
I have a parse rule like:
```
dotted_alpha = { (ASCII_ALPHA | ".")* ~ ASCII_ALPHA }
```

to parse strings which can contain any mix of "." and `ASCII_ALPHA` but the last char must be an `ASCII_ALPHA`.  However, I'm unable to parse this simple rule:

## test code
```
    #[test]
    fn test_dotted_alpha() {
        let s = "a.fa.gs.ab";
        let dotted_alpha = match NTriplesParser::parse(Rule::dotted_alpha, s) {
            Ok(mut da) => da.next().unwrap().as_str(),
            Err(e) => {
                println!("====== Err parsing dotted_alpha: {}", e);
                return;
            }
        };
        println!("got dotted_alpha: {}", dotted_alpha);
        assert_eq!(dotted_alpha, s);
    }
```

## output
```
====== Err parsing dotted_alpha:  --> 1:1
  |
1 | a.fa.gs.ab
  | ^---
  |
  = expected dotted_alpha
```

**Comment by nitingupta910** [comment]
I got it working with:
```
dotted_alpha = { (ASCII_ALPHA* ~ ".")* ~ ASCII_ALPHA+ }
```

This seems unintuitive and would be difficult to come up with when trying to translate an EBNF style grammar to PEG.

**Comment by CAD97** [comment]
Also, note that your PEG version is different from the BNF one: the BNF has no issue with multiple `.` in a row, whereas the PEG prohibits it.

The literal translation fails because of how PEG works. PEG is greedy: `(ASCII_ALPHA|".")*` will consume every single (ASCII) alphabetic character and period, and then the trailing `~ ASCII_ALPHA` won't have anything left to match.

**Comment by dragostis** [comment]
Closing this for now. Feel free to reopen it if you have more questions.
