### ISSUE TITLE
Grammar file not found on workspace

### ISSUE THREAD

**Issue by librelois** [pest-parser/pest#325]
I use pest in a crate of a workspace, so this crate has no `src` folder. I was forced to create an empty `src` subfolder in my crate so that pest could find my file, it's not clean.

It's easy to reproduce this bug, create a new workspace project and try to import pest grammar file from a crate of workspace.

**Comment by dragostis** [comment]
The question is, how does one solve this? It makes sense for the grammar file to be in `src` since that will make sure it's included in the crate.

**Comment by dragostis** [comment]
I think he means that it will not work where no `src` is present within a crate?

**Comment by librelois** [comment]
I have created an example repository that reproduces the bug.
If you clone the repository it does not compile. If you create an empty folder named `src` in `my-usb-crate` then it compiles.

https://github.com/librelois/workspace_use_pest

**Comment by librelois** [comment]
> The question is, how does one solve this?

My opinion is that the path should start from the root folder of the crate, and not from the sub-folder `src` :)

**Comment by CAD97** [comment]
Oh, that project is set up in a very unconventional manner.

Most workspaces are set up where each subcrate has a `src` directory containing the sources, rather than redefining where the entry point is in `Cargo.toml`.

Your problem isn't that you're in a workspace, but that you've defined a different `lib.path`.

<details><summary>A common workspace layout</summary>

```
/Cargo.toml
/derive/Cargo.toml
/derive/src/lib.rs
/derive/tests/test001.rs
/traits/Cargo.toml
/traits/src/lib.rs
```
</details>

---

Any change to where the `#[grammar = ""]` path starts from is technically a breaking change. The path is currently defined to be relative to the `src` directory, so for full strict backwards compatibility, that needs to be the default for a relative path.

One solution is to change the path to instead of being relative from `src`, to be relative from the directory of `lib.path` (`bin.path`?).

Another is to take a page from the JS world and use "anchored" paths: `#[grammar = "@/src/pest/grammar.pest"]`, where `@` is basically a "path macro" for `%CARGO_MANIFEST_DIR%`.

And another (poor?) solution is just to make the path `%CARGO_MANIFEST_DIR%/src/../{}` work even when `src` doesn't exist (and "just" collapsing isn't necessarily correct in the face of symlinks, thus why Rust's `canonicalize` currently uses the filesystem instead of being "simple").

**Comment by cramertj** [comment]
It's worth mentioning that https://github.com/pest-parser/pest/pull/360 was necessary because not all users are using cargo (and are missing the env vars relied upon here). IMO what this really wants is the ability to use `include!` and have it pre-expand before proc macros run. I'd consider opening an issue on rust-lang/rust, since this seems like a pretty reasonable thing to want and AFAIK there aren't a lot of great options at the moment.

**Comment by dragostis** [comment]
@cramertj, expending `include!`s before procedural macros are run would probably not be a stop-gap solution for our Cargo dependency. IMO the needed API is just being able to get the path of the file where the procedural macro resides. I've thought about opening an issue on Rust a while ago, but the procedural macros API was still heavily discussed.

**Comment by cramertj** [comment]
> string or a byte buffer.

I'd think you'd still want a `TokenStream` so that you can refer to `Span`s in the file and do error reporting using the normal API.

**Comment by seeekr** [comment]
Just want to leave a message here: Would be really nice to be able to use a path that does not start from the src/ dir. Use case: I'm using pest from a build.rs and thus don't really want my grammar file(s) be located in src/, which should contain only runtime code.

**Comment by brson** [comment]
I've hit this problem as well in a project where I'm not using the default cargo `src/` directory structure. I'd expect this file to be loaded relative to the directory the source file is contained in, similar to all the Rust builtin include-style macros.

I'm guessing its the way it is because plugins don't have access to the source location.

**Comment by dragostis** [comment]
@brson, precisely. I've thought about making a push for a way to get that in the procedural macro world, but I haven't really had time for it. FYI, you can also inline pest grammars right inside of the macro by providing the grammar inline. #360

**Comment by dwtj** [comment]
It also initially surprised and confused me that relative paths in `#[grammar = "..."]` are implicitly prefixed with `src/`.

I am using Pest in a project with a non-Cargo build system: *Bazel* (with `rules_rust` to define crates and `cargo-raze` to manage dependencies). Bazel Rust builds don't need to follow Cargo directory structure conventions like the use of `src/`.

Fortunately, similar to others, I can easily work around the issue by moving my grammar file to an otherwise empty `src/` subdirectory.

**Comment by Nukesor** [comment]
Hey :)

I just stumbled upon this issue and wanted to put in my 2 cents.

One of [my projects](https://github.com/Nukesor/pueue) has this issue at hand.
The project doesn't have a `src` folder, as it's split into two different namespaces that shouldn't have any knowledge about each other. However, they should still belong to the same crate, and thereby shouldn't be put into separate crates in a workspace.

Cargo also fully supports this scenario and using `src` is just a rough guideline.

I would really like to have the possibility to set the path to the parser file, without having to restructure the whole project.

In case you don't want to change the root of the path to `CARGO_MANIFEST_DIR` due to backward compatibility issues, I have an alternative proposal.

What do you think about:
- Resolving relative paths. I.e. allowing `../other/path`
- Add a new parameter which discovers from the root path: `gramar_from_root` (it's a stupid name, but just to give an idea)
