### ISSUE TITLE
support indent sensitive grammar?

### ISSUE THREAD

**Issue by Kilerd** [pest-parser/pest#328]
I want to use pest to write the indent sensitive grammar, like the one of python or YAML.
but it seems that pest does not have this capability.
I have searched a lot from Google, others said PEG cannot represent indentation.

like this very simple text:
```
a
    b
    b
        c
```
which means `a` has two children `b` and `b`, and second `b` has one child `c`
I don't know how to write its grammar and whether pest can do it or not.

**Comment by dragostis** [comment]
pest has the notion of a [stack](https://pest.rs/book/grammars/syntax.html#the-stack-wip) apart from the usual PEG syntax. With it, you can parse indentation-sensitive languages. We have a small [example](https://github.com/pest-parser/pest/blob/master/derive/tests/lists.pest) as a test.

**Comment by Kilerd** [comment]
Thanks a lot, it works.

**Comment by kevlarr** [comment]
@dragostis Pest has been incredible so far, and that lists sample has been remarkably helpful.

Why is the distinction between `top_first` and `top_continue` necessary? I'm pretty bad at this still, but I had assumed that, by the time it fully parses all indented children, the stack is empty because of the `DROP` and it should match a non-indented line without that (but obviously it doesn't).

**Comment by anibalanto** [comment]
Hello! Trying the @dragostis 's grammar I do a little change to it:
```
item = { (!"\n" ~ ANY)* }

lists = {lines ~ EOI }
lines = _{ top_first ~ ("\n" ~ top_continue)* }
top_first = _{ "- " ~ item ~ ("\n" ~ children)? }
top_continue = _{ PEEK_ALL ~ top_first }

indentation = _{ (" " | "\t")+ }
children = { PEEK_ALL ~ PUSH(indentation) ~ lines ~ DROP }
```
Thanks!
