### ISSUE TITLE
Build parser from grammar string at runtime

### ISSUE THREAD

**Issue by ZhangJianAo** [pest-parser/pest#432]
My program needs users to input the grammar and then parse another input data.

So I need to build a parser from a grammar string which user inputed, like this:

```
let parser = ParserFactory::build("number = { ASCII_DIGIT+ } ");
let pairs = parser::parse("number", "123 456").unwrap_or_else(|e| panic!("{}", e));
```

How can I do this?

**Comment by CAD97** [comment]
The normal pest derive that gives you a parser involves a lot of code generation that is infeasible to support at runtime (because Rust doesn't support runtime compilation of new code).

Instead, what you probably want is an interpreter. Pest does [have a VM interpreter](https://crates.io/crates/pest_vm), which is what is [used on the website](https://github.com/pest-parser/site/blob/master/src/main.rs).

Be aware that this is necessarily slower than the precompiled version, but it does work at runtime with arbitrary unknown grammars.

**Comment by birkenfeld** [comment]
> Pest does have a VM interpreter

It could be a tad better documented, though :)

**Comment by ZhangJianAo** [comment]
> The normal pest derive that gives you a parser involves a lot of code generation that is infeasible to support at runtime (because Rust doesn't support runtime compilation of new code).
> 
> Instead, what you probably want is an interpreter. Pest does [have a VM interpreter](https://crates.io/crates/pest_vm), which is what is [used on the website](https://github.com/pest-parser/site/blob/master/src/main.rs).
> 
> Be aware that this is necessarily slower than the precompiled version, but it does work at runtime with arbitrary unknown grammars.

Thank you so much! After viewing the website code, I figured out how to use VM, it soles my problem.

**Comment by lukthony** [comment]
> The normal pest derive that gives you a parser involves a lot of code generation that is infeasible to support at runtime (because Rust doesn't support runtime compilation of new code).
> 
> Instead, what you probably want is an interpreter. Pest does [have a VM interpreter](https://crates.io/crates/pest_vm), which is what is [used on the website](https://github.com/pest-parser/site/blob/master/src/main.rs).
> 
> Be aware that this is necessarily slower than the precompiled version, but it does work at runtime with arbitrary unknown grammars.

Excuse my ignorance here but, on the website, I find myself bumping into left-recursion, for which the error directs me to PrattParser. Would using VM and PrattParser in conjunction be possible, @CAD97?
