### ISSUE TITLE
Is there a CLI tool transforming a pest file into rust files?

### ISSUE THREAD

**Issue by KOLANICH** [pest-parser/pest#464]

**Comment by sirxyzzy** [comment]
I don't know of a dedicated tool, the issue is that the code is generated on the fly, via Rust macros, however, you get the generated code if you want to review it, by running "cargo-expand" (although it seems to take quite a long time to run...)

See https://github.com/dtolnay/cargo-expand for details

**Comment by KOLANICH** [comment]
Thanks for the info.
