### ISSUE TITLE
Using PrecClimber requires grammar modifications

### ISSUE THREAD

**Issue by GrantMoyer** [pest-parser/pest#510]
Right now, `PrecClimber` can only determine operator precedence based on `Rule` enums. This partly defeats the point of `PrecClimber`, because ideally adding an operator shouldn't require changing the grammar, but as it stands at least one new rule needs to be added to the grammar for each operator.

Instead of `PrecClimber` taking a `Vec<Operator<Rule>>`, it could take a function from operator pair to precedence, `FnMut(Pair<Rule>) -> Option<Precedence>`, where `struct Precedence(i32, Assoc)`.

This would allow having a rule in the grammar like `operator = {"+" | "-" | "*" | "/" }`,  and a corresponding function:

```rust
fn prec(op: Pair<Rule>) -> Precedence {
    match op.as_str() {
        "+" | "-" => Some(Precedence(1, Assoc::Left)),
        "*" | "/" => Some(Precedence(2, Assoc::Left)),
        _ => None,
    }
}
```

**Comment by tomtau** [comment]
`PrecClimber` is deprecated, there's a `PrattParser` now. It has a bit different API: https://docs.rs/pest/latest/pest/pratt_parser/struct.PrattParser.html# if this issue is still relevant to it (I guess it may be, because it still takes rule types for the precedence), feel free to reopen it in the context of its API
