### ISSUE TITLE
Add buffered file input.

### ISSUE THREAD

**Issue by dragostis** [pest-parser/pest#6]

**Comment by Keats** [comment]
Am i right in thinking you want a `buffered_file_input.rs` in the `inputs` directory similar to the current `string_input`?

It would take a path, use https://doc.rust-lang.org/std/io/struct.BufReader.html to `read_to_end()` and return a `StringInput` (for simplicity, will need to see if benchmarks are ok)?

If that's the case it seems that it could be left to the application to do that rather than Pest, unless it's a very common pattern.
Let me know if it is correct

**Comment by dragostis** [comment]
That is correct, the only issue here is that `BufReader` may not work because of the way the matching methods are implemented in `Input`, so you may have to implement buffering manually.
