### ISSUE TITLE
Breaking change between 2.1 and 2.4/2.5

### ISSUE THREAD

**Issue by vincent-herlemont** [pest-parser/pest#762]
**Describe the bug**

During this discussion [Implicit expression ·  #761](https://github.com/pest-parser/pest/discussions/761) I have discovered that there is a difference of behavior for the following syntax between pest 2.1 and pest 2.4/2.5, for now I don't know if it's the expected behavior or not. I open an issue to know how to decide this.

**To Reproduce**
For the following grammar:
```bash
program = _{ SOI ~ implicit ~ EOI  }
implicit= ${ or ~ (WHITESPACE+ ~ or )* }

or  = !{ and ~ (or_op ~ and)+ | and }
and = { comp ~ (and_op ~ comp)+ | comp }
comp = { array ~ eq_op ~ array | array }

array = ${ term }

term = _{ ASCII_ALPHANUMERIC+ }
or_op = { "||" }
and_op = { "&&" }
eq_op = { "=" }
WHITESPACE = _{ " " | "\t" | NEWLINE }
```

The input `a a` return this error for pest 2.4/2.5 :x: :
```bash
 --> 1:3
  |
1 | a a
  |   ^---
  |
  = expected EOI, or_op, and_op, or eq_op
```

Success for 2.1 :heavy_check_mark: 

**Expected behavior**

Run without error and return two `array`.

**Comment by tomtau** [comment]
It may be a side-effect of some optimization work that has been done since 2.1, e.g. https://github.com/pest-parser/pest/pull/473 ?

**Comment by tomtau** [comment]
@vincent-herlemont I managed to reproduce it. I tried `git bisect` to find the commit where it stopped parsing and it turned out to be this one b720edcd0385d8e4965b4da06f92efd01edb33e9 from that optimization PR #473.
If my understanding is correct, that optimization will try to rewrite rules of the form `a ~ b | a` to `a ~ b?` which seems reasonable on its own, but I guess it may be problematic in some contexts due to the greedy backtracking nature of parsing here.

@SkiFire13 @dragostis @CAD97 do you have any suggestions on how to proceed here -- should that optimization be reverted, or should it stay as it is and @vincent-herlemont could rewrite that grammar in some way (I guess one dummy workaround is to introduce extra rules, so that the optimization fails to be applied), or can you see an easy way to restrict that optimization?

**Comment by CAD97** [comment]
Transforming `a ~ b | a` to `a ~ b?` is incorrect when implicit whitespace is on, yeah. Generally the consistency/predicability of whitespace behavior is really not great.

With the implied whitespace made explicit, it's transforming

```rust
@{ a ~ WHITESPACE* ~ b | a }
// to
@{ a ~ WHITESPACE* ~ b? }
// which is incorrect, it should be
@{ a ~ (WHITESPACE* ~ b)? }
```

Probably the "correct" fix is to "desugar" all of the implicit whitespace rules before applying any optimization transformations.

**Comment by tomtau** [comment]
made a quick fix in https://github.com/pest-parser/pest/pull/766
There are two follow ups:
1. (if possible) writing up a fuzzer that will try to fuzz grammar+input, and check the parser results of the optimized and non-optimized rules match;
2. fixing the optimizer: the way forward is probably what @dragostis mentioned before with [egg](https://egraphs-good.github.io/) and [ruler](https://github.com/uwplse/ruler), but that probably only works for a cleaned up / simpler meta grammar, i.e. [pest3](https://github.com/pest-parser/pest3)

**Comment by vincent-herlemont** [comment]
@tomtau Thanks for the fix :) !
